views/band.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *
from datetime import datetime

band_bp = Blueprint('band', __name__)


@band_bp.route("/band/")
def index():
    bands = invoke(f'''
                   select 
                   exists (
                       select * from LikeBand where UserID = {session['userid']} and BandID = b.BandID
                   ) as liked,
                   b.* from Band b;''').fetchall()
    print(bands)
    return render_template("/band/index.html", bands=bands)

@band_bp.route("/band/new", methods=['GET', 'POST'])
def new():
    if request.method == 'GET':
        return render_template('band/new.html')
    
    userid = session['userid']
    name = request.form.get('name')
    desc = request.form.get('description')
    date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    band_id = invoke_insertion(f'insert into Band(BandName, BandDescription, FormationDate) values ("{name}", "{desc}", "{date}");')
    invoke(f'insert into _UserToBand(UserID, BandID, Role) values("{userid}", "{band_id}", "creator")')
    return redirect(url_for('band.details', id=band_id))

@band_bp.route('/band/<int:id>/')
def details(id: int):
    band = invoke(f'select * from Band where BandId = {id}').fetchone()
    if band is None:
        abort(404)

    members = invoke(f'''select * from User user where exists (
                     select * from _UserToBand where UserID = user.UserID and BandID = {id}
                     )''').fetchall()
    concerts = invoke(f'select * from Concert where BandID = {id}').fetchall()
    rel = invoke(f'select Role from _UserToBand where UserID = {session['userid']} and BandID = {id}').fetchone()
    liked_count = invoke(f'select count(*) as `count` from LikeBand where BandID = {id}').fetchone()
    if liked_count is None:
        liked_count = { 'count': 0 }
    editable = (rel is not None) or session['usertype'] == 'manager'
    joined = rel is not None

    return render_template('/band/details.html', band=band, members=members, concerts=concerts, liked_count=liked_count, editable=editable, joined=joined)

@band_bp.route('/band/<int:id>/join', methods=['GET', 'POST'])
def join(id: int):
    band = invoke(f'select * from Band where BandId = {id}').fetchone()
    if band is None:
        abort(404)

    rel = invoke(f'select * from _UserToBand where UserID = {session['userid']} and BandID = {id}').fetchone()

    if request.method == 'GET':
        joined = rel is not None
        return render_template('/band/join.html', band=band, joined=joined)

    if rel is None:
        invoke(f'insert into _UserToBand(UserID, BandID) values ({session['userid']}, {id})')
        return redirect(url_for('band.details', id=id))
    else:
        invoke(f'delete from _UserToBand where UserID = {session['userid']} and BandID = {id}')
        return redirect(url_for('band.index'))


@band_bp.route('/band/<int:id>/like', methods=['POST'])
def like(id: int):
    userid = session['userid']

    rel = invoke(f'select * from LikeBand where UserID = {userid} and BandID = {id}').fetchone()

    if rel is None:
        invoke(f'insert into LikeBand values ({userid}, {id})')
        return { 'liked': True }
    else:
        invoke(f'delete from LikeBand where UserID = {userid} and BandID = {id}')
        return { 'liked': False }


@band_bp.route('/band/<int:id>/edit', methods=['GET', 'POST'])
def edit(id: int):
    if request.method == 'GET':
        band = invoke(f'select * from Band where BandId = {id}').fetchone()
        if band is None:
            abort(404)

        return render_template('/band/edit.html', band=band)
    
    name = request.form.get('name')
    desc = request.form.get('description')

    invoke(f'update Band set BandName="{name}", BandDescription="{desc}" where BandID={id}')
    return redirect(url_for('band.details', id=id))

templates/band/details.html
{% extends '_base.html' %}

{% block title %}乐队详情 - {{ band.BandName }}{% endblock %}

{% block body %}
<h1 class="ui centered header">
    乐队详情 - {{ band.BandName }}
</h1>
<div class="ui segment">

    <p>ID: {{ band.BandID }}</p>
    <p>乐队名: {{ band.BandName }}</p>
    <p>描述: {{ band.BandDescription }}</p>
    <p>创建于: {{ band.FormationDate }}</p>

    <p>成员：</p>

    <div class="ui bulleted list">
        {% for user in members %}
        <div class="item">{{ user.UserName }}</div>
        {% endfor %}
    </div>

    <p>演出列表：</p>
    <div class="ui bulleted list">
        {% for item in concerts %}
        <div class="item"><a href="{{ url_for('concert.details', id=item.ConcertID) }}">{{ item.ConcertName }}</a></div>
        {% else %}
        <div class="item"><i>暂无</i></div>
        {% endfor %}

    </div>

    <p>共 {{ liked_count.count }} 位喜欢 {{ band.BandName }} 的用户</p>

    {% if editable %}
    <a class="ui primary button" href="{{ url_for('band.edit', id=band.BandID) }}">
        <i class="icon edit"></i>
        编辑信息
    </a>
    {% endif %}
    
    <a class="ui primary button" href="{{ url_for('band.join', id=band.BandID) }}">
        {% if joined %}
        退出乐队
        {% else %}
        加入乐队
        {% endif %}
    </a>

</div>
{% endblock %}

templates/band/edit.html
{% extends '_base.html' %}

{% block title %}新建乐队{% endblock %}

{% block body %}
<div class="ui centered grid">
    <div class="eight wide column">
        <div class="ui segment">
            <form action="" method="post" class="ui form">
                <div class="field">
                    <label>乐队名</label>
                    <input type="text" name="name" value="{{ band.BandName }}" required>
                </div>
                <div class="field">
                    <label>描述</label>
                    <input type="text" name="description" value="{{ band.BandDescription }}" required>
                </div>
                <button class="ui primary button">
                    提交
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/band/index.html
{% extends '_base.html' %}

{% block title %}乐队列表{% endblock %}

{% block body %}
<h1 class="ui centered header">
    乐队列表
</h1>

{% if session.usertype != 'fan' %}
<div style="display: flex; flex-direction: row; justify-content: flex-end;">
    <a class="ui primary button" href="{{ url_for('band.new') }}">
        <i class="icon plus"></i>
        创建乐队
    </a>
</div>
{% endif %}

<table class="ui celled table">
    <thead>
        <tr>
            <th>乐队名</th>
            <th>乐队简介</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for band in bands %}
        <tr>
            <td><a href="{{ url_for('band.details', id=band.BandID) }}">{{ band.BandName }}</a></td>
            <td>{{ band.BandDescription }}</td>
            <td>
                <button class="ui icon button like-button" data-band-id="{{ band.BandID }}"
                    data-liked="{{ band.liked }}">
                    {% if band.liked %}
                    <i class="heart icon"></i>
                    {% else %}
                    <i class="heart outline icon"></i>
                    {% endif %}
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    $('.like-button').click(function () {
        $(this).addClass('disabled');
        const bandId = $(this).data('band-id');
        fetch('{{ url_for("band.like", id=114514)}}'.replace('114514', bandId), {
            method: 'POST'
        })
            .then(response => response.json())
            .then(data => {
                $(this).removeClass('disabled');
                if (data.liked === false) {
                    $(this).find('i.icon').addClass('outline');
                }
                else {
                    $(this).find('i.icon').removeClass('outline');
                }
            });
    });
</script>
{% endblock %}

templates/band/join.html
{% extends '_base.html' %}

{% block title %}加入乐队{% endblock %}

{% block body %}

<div class="ui segment">
    {% if joined %}
    <p>您即将离开 {{ band.BandName }}</p>
    {% else %}
    <p>您即将加入 {{ band.BandName }}</p>
    {% endif %}
    <form class="ui form" action="" method="post">
        <button class="ui primary button">
            <i class="check icon"></i>
            确认
        </button>
    </form>
</div>

{% endblock %}

templates/band/new.html
{% extends '_base.html' %}

{% block title %}新建乐队{% endblock %}

{% block body %}
<h1 class="ui centered header">
    新建乐队
</h1>

<div class="ui centered grid">
    <div class="eight wide column">
        <div class="ui segment">

            <form action="" method="post" class="ui form">
                <div class="field">
                    <label>乐队名</label>
                    <input type="text" name="name" required>
                </div>
                <div class="field">
                    <label>描述</label>
                    <input type="text" name="description" required>
                </div>
                <button class="ui primary button">
                    提交
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}