views/concert.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *

concert_bp = Blueprint('concert', __name__)

@concert_bp.route('/concert/')
def index():
    concerts = invoke(f'''select
                      exists (select * from Participation where UserID = {session['userid']} and Participation.ConcertID = Concert.ConcertID) as participated,
                      Concert.*, Band.* from Concert
                      inner join Band on Concert.BandID = Band.BandID;''').fetchall()
    return render_template('/concert/index.html', concerts=concerts)

@concert_bp.route('/concert/new', methods=['GET', 'POST'])
def new():
    if request.method == 'GET':
        userid = session['userid']
        bands = invoke(f'''select * from Band b where exists (
                       select * from _UserToBand where UserID = {userid} and BandID = b.BandID
                       )''')
        return render_template('/concert/new.html', bands=bands)
    
    name = request.form['name']
    location = request.form['location']
    date = request.form['date']
    band_id = request.form['band_id']

    concert_id = invoke_insertion(f'''insert into Concert(ConcertName, Location, ConcertDate, BandID)
                                  VALUES ("{name}", "{location}", "{date}", {band_id})''')
    
    return redirect(url_for('concert.details', id=concert_id))
    
    
@concert_bp.route('/concert/<int:id>')
def details(id: int):
    concert = invoke(f'select * from Concert where ConcertID = {id}').fetchone()

    if concert is None:
        abort(404)

    band = invoke(f'select * from Band where BandID = {concert['BandID']}').fetchone()
    rel = invoke(f'select * from _UserToBand where BandID = {concert['BandID']} and UserID = {session['userid']}').fetchone()
    part = invoke(f'select * from Participation where ConcertID = {id} and UserID = {session['userid']}').fetchone()
    editable = (rel is not None) or session['usertype'] == 'manager'

    return render_template('/concert/details.html', concert=concert, band=band, participation=part, editable=editable)

@concert_bp.route('/concert/<int:id>/edit', methods=['GET', 'POST'])
def edit(id: int):
    if request.method == 'GET':
        userid = session['userid']

        concert = invoke(f'select * from Concert where ConcertID = {id}').fetchone()

        if concert is None:
            abort(404)

        bands = invoke(f'''select * from Band b where exists (
                       select * from _UserToBand where UserID = {userid} and BandID = b.BandID
                       )''')

        return render_template('/concert/edit.html', concert=concert, bands=bands)
    
    name = request.form['name']
    location = request.form['location']
    date = request.form['date']
    band_id = request.form['band_id']

    invoke(f'update Concert set ConcertName="{name}", Location="{location}", ConcertDate="{date}", BandID={band_id} where ConcertID={id}')

    return redirect(url_for('concert.details', id=id))

@concert_bp.route('/concert/<int:id>/delete')
def delete(id: int):
    userid = session['userid']
    concert = invoke(f'select * from Concert where ConcertID = {id}').fetchone()

    rel = invoke(f'select * from _UserToBand where BandID = {concert['BandID']} and UserID = {userid}').fetchone()

    if rel is None:
        abort(403)

    invoke(f'delete from Concert where ConcertID = {id}')

    return redirect(url_for('concert.index'))

@concert_bp.route('/concert/<int:id>/join', methods=['GET', 'POST'])
def join(id: int):
    if request.method == 'GET':
        concert = invoke(f'select * from Concert where ConcertID = {id}').fetchone()

        if concert is None:
            abort(404)

        return render_template('/concert/join.html', concert=concert)
    
    ticket = request.form['ticket']

    invoke(f'''insert into Participation(ConcertID, UserID, TicketNumber)
           values ({id}, {session['userid']}, "{ticket}")''')
    return redirect(url_for('concert.details', id=id))

templates/concert/details.html
{% extends '_base.html' %}

{% block title %}演出详情 - {{ concert.ConcertName }}{% endblock %}

{% block body %}
<h1 class="ui centered header">
    演出详情 - {{ concert.ConcertName }}
</h1>
<div class="ui segment">

    <p>ID: {{ concert.ConcertID }}</p>
    <p>演出名: {{ concert.ConcertName }}</p>
    <p>参演乐队: <a href="{{ url_for('band.details', id=band.BandID) }}">{{ band.BandName }}</a></p>
    <p>演出地点: {{ concert.Location }}</p>
    <p>演出时间: {{ concert.ConcertDate }}</p>

    {% if participation is none %}
    <a class="ui button" href="{{ url_for('concert.join', id=concert.ConcertID) }}">
        参加演出
    </a>
    {% else %}
    <p>您的票号: {{ participation.TicketNumber }}</p>
    {% endif %}


    {% if editable %}
    <a class="ui primary button" href="{{ url_for('concert.edit', id=concert.ConcertID) }}">
        <i class="edit icon"></i>
        编辑信息
    </a>
    <a class="ui red button" href="{{ url_for('concert.delete', id=concert.ConcertID) }}">
        <i class="ban icon"></i>
        删除演出
    </a>
    {% endif %}
</div>
{% endblock %}

templates/concert/edit.html
{% extends '_base.html' %}

{% block title %}编辑演出{% endblock %}

{% block body %}
<div class="ui centered grid">
    <div class="eight wide column">
        <div class="ui segment">

            <form action="" method="post" class="ui form">
                <div class="field">
                    <label>演出名</label>
                    <input type="text" name="name" required value="{{ concert.ConcertName }}">
                </div>
                <div class="field">
                    <label>参演乐队</label>
                    <div class="ui selection dropdown">
                        <input type="hidden" name="band_id" required value="{{ concert.BandID }}">
                        <i class="dropdown icon"></i>
                        <div class="text"></div>
                        <div class="menu">
                            {% for band in bands %}
                            <div class="item" data-value="{{ band.BandID }}">{{ band.BandName }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label>演出地点</label>
                    <input type="text" name="location" required value="{{ concert.Location }}">
                </div>
                <div class="field">
                    <label>演出时间</label>
                    <input type="datetime-local" name="date" required value="{{ concert.ConcertDate }}">
                </div>
                <button class="ui primary button">
                    提交
                </button>
            </form>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('.ui.dropdown').dropdown();
    });
</script>
{% endblock %}

templates/concert/index.html
{% extends '_base.html' %}

{% block title %}演出列表{% endblock %}

{% block body %}

<h1 class="ui centered header">
    演出列表
</h1>

{% if session.usertype != 'fan' %}
<div style="display: flex; flex-direction: row; justify-content: flex-end;">
    <a class="ui primary button" href="{{ url_for('concert.new') }}">
        <i class="icon plus"></i>
        新建演出
    </a>
</div>
{% endif %}

<table class="ui celled table">
    <thead>
        <tr>
            <th>演出名</th>
            <th>演出时间</th>
            <th>参演乐队</th>
            <th>演出地点</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for item in concerts %}
        <tr>
            <td><a href="{{ url_for('concert.details', id=item.ConcertID) }}">{{ item.ConcertName }}</a></td>
            <td>{{ item.ConcertDate }}</td>
            <td><a href="{{ url_for('band.details', id=item.BandID) }}">{{ item.BandName }}</a></td>
            <td>{{ item.Location }}</td>
            <td>
                {% if item.participated %}
                <i>您已参加</i>
                {% else %}
                <a href="{{ url_for('concert.join', id=item.ConcertID) }}" class="ui icon button">
                    <i class="plus icon"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/concert/join.html
{% extends '_base.html' %}

{% block title %}参加演出{% endblock %}

{% block body %}
<div class="ui centered grid">
    <div class="eight wide column">
        <h1 class="ui header">
            您将参加 {{ concert.ConcertName }}
        </h1>
        <div class="ui segment">

            <form action="" method="post" class="ui form">
                <div class="field">
                    <label>票号</label>
                    <input type="text" name="ticket" required>
                </div>
                <button class="ui primary button">
                    提交
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/concert/new.html
{% extends '_base.html' %}

{% block title %}新建演出{% endblock %}

{% block body %}

<h1 class="ui centered header">
    新建演出
</h1>

<div class="ui centered grid">
    <div class="eight wide column">
        <div class="ui segment">

            <form action="" method="post" class="ui form">
                <div class="field">
                    <label>演出名</label>
                    <input type="text" name="name" required>
                </div>
                <div class="field">
                    <label>参演乐队</label>
                    <div class="ui selection dropdown">
                        <input type="hidden" name="band_id" required>
                        <i class="dropdown icon"></i>
                        <div class="text"></div>
                        <div class="menu">
                            {% for band in bands %}
                            <div class="item" data-value="{{ band.BandID }}">{{ band.BandName }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label>演出地点</label>
                    <input type="text" name="location" required>
                </div>
                <div class="field">
                    <label>演出时间</label>
                    <input type="datetime-local" name="date" required>
                </div>
                <button class="ui primary button">
                    提交
                </button>
            </form>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('.ui.dropdown').dropdown();
    });
</script>
{% endblock %}