views/album.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *
from datetime import datetime

album_bp = Blueprint('album', __name__)


@album_bp.route('/album/')
def index():
    albums = invoke(f'''
                    select (
                        select count(*) from Song where Song.AlbumID = Album.AlbumID
                    ) as count, 
                    exists (
                        select * from LikeAlbum where UserID = {session['userid']} and AlbumID = Album.AlbumID
                    ) as liked,
                    Album.*, Band.* from Album
                    inner join Band on Album.BandID = Band.BandID''').fetchall()

    return render_template('/album/index.html', albums=albums)


@album_bp.route('/album/new', methods=['GET', 'POST'])
def new():
    if request.method == 'GET':
        userid = session['userid']
        bands = invoke(f'''select * from Band b where exists (
                       select * from _UserToBand where UserID = {userid} and BandID = b.BandID
                       )''')
        return render_template('/album/new.html', bands=bands)
    
    if not request.is_json:
        abort(400)

    data = request.json
    name = data['name']
    desc = data['desc']
    band_id = data['bandId']
    date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    album_id = invoke_insertion(f'''insert into Album(AlbumName, AlbumDescription, ReleaseDate, BandID)
                                    values ("{name}", "{desc}", "{date}", {band_id})''')
    
    for i, item in enumerate(data['songs']):
        name = item['name']
        genre = item['genre']
        author = item['originalAuthor']
        invoke_insertion(f'''insert into Song(SongName, OriginalAuthor, Genre, AlbumID, `Order`)
                             values ("{name}", "{author}", "{genre}", {album_id}, {i + 1})''')
        
    return redirect(url_for('album.details', id=album_id))

@album_bp.route('/album/<int:id>')
def details(id: int):
    album = invoke(f'select * from Album where AlbumID = {id}').fetchone()

    if album is None:
        abort(404)

    rating = invoke(f'select AlbumID, avg(Rating) as rating, count(*) as `count` from Review group by AlbumID having AlbumID = {id}').fetchone()

    songs = invoke(f'select * from Song where AlbumID = {id} order by `Order` asc')
    user_review = invoke(f'select * from Review where AlbumID = {id} and UserID = {session['userid']}').fetchone() 
    liked_users = invoke(f'''select * from User user where exists (
                         select * from LikeAlbum where UserID = user.UserID and AlbumID = {id}
                         )''').fetchall()
    rel = invoke(f'select * from _UserToBand where BandID = {album['BandID']} and UserID = {session['userid']}').fetchone()
    
    editable = rel is not None or session['usertype'] == 'manager'

    return render_template('/album/details.html', album=album, songs=songs, rating=rating, user_review=user_review, liked_users=liked_users, editable=editable)

@album_bp.route('/album/<int:id>/like', methods=['POST'])
def like(id: int):
    userid = session['userid']

    rel = invoke(f'select * from LikeAlbum where UserID = {userid} and AlbumID = {id}').fetchone()

    if rel is None:
        invoke(f'insert into LikeAlbum values ({userid}, {id})')
        return { 'liked': True }
    else:
        invoke(f'delete from LikeAlbum where UserID = {userid} and AlbumID = {id}')
        return { 'liked': False }
    
@album_bp.route('/album/<int:id>/add', methods=['GET', 'POST'])
def add(id: int):
    if request.method == 'GET':
        album = invoke(f'select * from Album where AlbumID = {id}')
        songs = invoke(f'select * from Song where AlbumID = {id} order by `Order` asc').fetchall()
        return render_template('/album/add.html', album=album, songs=songs)
    
    pos = request.form['pos']
    name = request.form['name']
    oa = request.form['originalAuthor']
    genre = request.form['genre']

    invoke(f'update Song set `Order` = `Order` + 1 where AlbumID = {id} and `Order` > {pos}')
    invoke(f'''insert into Song(SongName, OriginalAuthor, Genre, AlbumID, `Order`)
           values ("{name}", "{oa}", "{genre}", {id}, {pos + 1})''')
    
    return redirect(url_for('album.details', id=id))

views/review.py
from flask import render_template, request, redirect, url_for, session, abort, Blueprint
from db import *

review_bp = Blueprint('review', __name__)

@review_bp.route('/review')
def index():
    reviews = invoke(f'''select * from Review
                     inner join Album on Album.AlbumID = Review.AlbumID
                     inner join User on User.UserID = Review.UserID''')
    
    return render_template('review/index.html', reviews=reviews)

@review_bp.route('/album/<int:album_id>/review/<int:user_id>')
def details(album_id: int, user_id: int):
    review = invoke(f'''select * from Review
                    inner join Album on Album.AlbumID = Review.AlbumID
                    inner join User on User.UserID = Review.UserID
                    where Review.AlbumID = {album_id} and Review.UserID = {user_id}''').fetchone()
    
    if review is None:
        abort(404)

    editable = review['UserID'] == session['userid'] or session['usertype'] == 'manager'

    return render_template('/review/details.html', review=review, editable=editable)

@review_bp.route('/album/<int:album_id>/review/')
def list(album_id: int):
    album = invoke(f'select * from Album where AlbumID = {album_id}').fetchone()

    if album is None:
        abort(404)

    reviews = invoke(f'''select * from Review
                       inner join User on Review.UserID = User.UserID
                       where AlbumID = {album_id}''')
    return render_template('/review/list.html', album=album, reviews=reviews)

@review_bp.route('/album/<int:album_id>/review/new', methods=['GET', 'POST'])
def new(album_id: int):
    if request.method == 'GET':
        album = invoke(f'select * from Album where AlbumID = {album_id}')
        return render_template('/review/new.html', album=album)
    
    rating = request.form['rating']
    comment = request.form['comment']

    invoke(f'''insert into Review(AlbumID, UserID, Rating, Comment)
           values ({album_id}, {session['userid']}, {rating}, "{comment}")''')
    
    return redirect(url_for('review.details', album_id=album_id, user_id=session['userid']))
    
@review_bp.route('/album/<int:album_id>/review/edit', methods=['GET', 'POST'])
def edit(album_id: int):
    if request.method == 'GET':
        review = invoke(f'''select * from Review
                          inner join Album on Album.AlbumID = Review.AlbumID
                          where Review.AlbumID = {album_id} and Review.UserID = {session['userid']}''').fetchone()
        
        if review is None:
            return redirect(url_for('review.new', album_id=album_id))
        
        return render_template('review/edit.html', review=review)
    
    rating = request.form['rating']
    comment = request.form['comment']

    invoke(f'''update Review set Rating = {rating}, Comment = "{comment}"
               where AlbumID = {album_id} and UserID = {session['userid']}''')

    return redirect(url_for('review.details', album_id=album_id, user_id=session['userid']))

templates/album/add.html
{% extends '_base.html' %}

{% block title %}添加歌曲 - {{ album.AlbumName }}{% endblock %}

{% block body %}

<div class="ui segment">
    <div class="ui centered grid">
        <div class="eight wide column">
            <p>当前曲目：</p>

            {% for song in songs %}
            <p>{{ song.Order }}. {{ song.OriginalAuthor }} - {{ song.SongName }}</p>
            {% endfor %}
            <form class="ui form" action="" method="post">
                <div class="field">
                    <label>插入位置 (插入后，该位置的歌曲将排在新插入的歌曲之前)</label>
                    <input type="number" name="pos" min="0" max="{{ songs | length }}" required>
                </div>
                <div class="field">
                    <label>曲目标题</label>
                    <input type="text" name="name" required>
                </div>
                <div class="field">
                    <label>原作者</label>
                    <input type="text" name="originalAuthor">
                </div>
                <div class="field">
                    <label>曲风</label>
                    <input type="text" name="genre">
                </div>

                <button class="ui primary button">
                    确认更改
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/album/details.html
{% extends '_base.html' %}

{% block title %}专辑详情 - {{ album.AlbumName }}{% endblock %}

{% block body %}
<div class="ui segment">
    <p>专辑ID: {{ album.AlbumID }}</p>
    <p>专辑名: {{ album.AlbumName }}</p>
    <p>专辑简介: {{ album.AlbumDescription }}</p>
    <p>曲目列表: </p>

    <div class="ui bulleted list">
        {% for song in songs %}

        <div class="item">
            <a href="{{ url_for('song.details', id=song.SongID) }}">{{ song.Order }}. {{ song.OriginalAuthor }} - {{ song.SongName }}</a>
        </div>
        {% endfor %}
    </div>

    <p>喜欢 {{ album.AlbumName }} 的用户：</p>
    <div class="ui bulleted list">
        {% for user in liked_users %}
        <div class="item">
            {{ user.UserName }}
        </div>
        {% else %}
        <div class="item"><i>暂无</i></div>
        {% endfor %}
    </div>

    <p>
        评分：
        {% if rating is none %}
        <i>null</i>
        {% else %}
        {{ rating.rating }}, 共 {{ rating.count }} 人评分
        {% endif %}
    </p>

    {% if user_review is none %}
    <a class="ui primary button" href="{{ url_for('review.new', album_id=album.AlbumID) }}">
        <i class="edit icon"></i>
        撰写乐评
    </a>
    {% else %}
    <p>您的评价：{{ user_review.Rating }} {{ user_review.Comment }}</p>
    {% endif %}

    <a class="ui primary button" href="{{ url_for('review.list', album_id=album.AlbumID) }}">
        所有乐评
    </a>
    
    {% if editable %}
    <a class="ui primary button" href="{{ url_for('album.add', id=album.AlbumID) }}">
        <i class="plus icon"></i>
        添加歌曲
    </a>
    {% endif %}
</div>
{% endblock %}

templates/album/index.html
{% extends '_base.html' %}

{% block title %}专辑列表{% endblock %}

{% block body %}

<h1 class="ui centered header">
    专辑列表
</h1>

{% if session.usertype != 'fan' %}
<div style="display: flex; flex-direction: row; justify-content: flex-end;">
    <a class="ui primary button" href="{{ url_for('album.new') }}">
        <i class="icon plus"></i>
        新建专辑
    </a>
</div>
{% endif %}

<table class="ui celled table">
    <thead>
        <tr>
            <th>专辑名</th>
            <th>乐队</th>
            <th>曲目数</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for album in albums %}
        <tr>
            <td><a href="{{ url_for('album.details', id=album.AlbumID) }}">{{ album.AlbumName }}</a></td>
            <td>{{ album.BandName }}</td>
            <td>{{ album.count }}</td>
            
            <td>
                <button class="ui icon button like-button" data-album-id="{{ album.AlbumID }}"
                    data-liked="{{ album.liked }}">
                    {% if album.liked %}
                    <i class="heart icon"></i>
                    {% else %}
                    <i class="heart outline icon"></i>
                    {% endif %}
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    $('.like-button').click(function () {
        $(this).addClass('disabled');
        const bandId = $(this).data('album-id');
        fetch('{{ url_for("album.like", id=114514)}}'.replace('114514', bandId), {
            method: 'POST'
        })
            .then(response => response.json())
            .then(data => {
                $(this).removeClass('disabled');
                if (data.liked === false) {
                    $(this).find('i.icon').addClass('outline');
                }
                else {
                    $(this).find('i.icon').removeClass('outline');
                }
            });
    });
</script>
{% endblock %}

templates/album/new.html
{% extends '_base.html' %}

{% block title %}新建专辑{% endblock %}

{% block body %}
<div class="ui segment">

    <div class="ui centered grid">
        <div class="ten wide column">
            <form class="ui form" id="album-detail">
                <div class="field">
                    <label>专辑名</label>
                    <input type="text" name="name" required id="album-name">
                </div>
                <div class="field">
                    <label>描述</label>
                    <input type="text" name="description" id="album-desc">
                </div>
                <div class="field">
                    <label>归属乐队</label>
                    <div class="ui selection dropdown">
                        <input type="hidden" name="band_id" required id="album-band-id">
                        <i class="dropdown icon"></i>
                        <div class="text"></div>
                        <div class="menu">
                            {% for band in bands %}
                            <div class="item" data-value="{{ band.BandID }}">{{ band.BandName }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="ui divider"></div>
    <div class="ui centered divided grid">
        <div class="six wide column">
            <button class="ui primary button" onclick="add()">
                <i class="plus icon"></i>
                添加歌曲
            </button>

            <div class="ui secondary vertical fluid menu" id="song-list">

            </div>
        </div>

        <div class="ten wide column">
            <form class="ui form" id="song-detail">
                <div class="field">
                    <label>曲目标题</label>
                    <input type="text" name="name" required>
                </div>
                <div class="field">
                    <label>原作者</label>
                    <input type="text" name="originalAuthor">
                </div>
                <div class="field">
                    <label>曲风</label>
                    <input type="text" name="genre">
                </div>

                <button class="ui primary button" type="button" id="button-apply">
                    确认更改
                </button>
            </form>
        </div>
    </div>

    <div class="ui divider"></div>

    <button class="ui primary fluid button" id="button-submit">
        <i class="check icon"></i> 提交
    </button>
</div>


<script>
    $(function () {
        $('.ui.dropdown').dropdown();
    });
    let selected = null;
    const songs = [];

    function sync() {
        $('#song-list').html('');

        songs.forEach((song, index) => {
            const element = $(`
            <a class="${index === selected ? 'active ' : ''}item">
                <h3 class="ui header">${song.name}</h3>
                <p class="ui secondary">by ${song.originalAuthor}</p>
                <button class="ui red icon button">
                    <i class="ban icon"></i>
                </button>
            </a>`);
            element.children('button').click(() => remove(index));
            element.click(() => select(index));
            element.appendTo('#song-list');
        });

        if (selected === null) {
            $('#song-detail').find('.field').addClass('disabled');
        }
        else {
            $('#song-detail').find('.field').removeClass('disabled');
        }
    }

    function remove(index) {
        selected = null;
        songs.splice(index, 1);
        sync();
    }

    function select(index) {
        selected = index;
        const form = $('#song-detail');

        form.find('input[name="name"]').val(songs[selected].name);
        form.find('input[name="genre"]').val(songs[selected].genre);
        form.find('input[name="originalAuthor"]').val(songs[selected].originalAuthor);

        sync();
    }

    function add() {
        songs.push({
            name: 'Unnamed',
            genre: 'Genre',
            originalAuthor: 'Artist'
        });
        select(songs.length - 1);
    }

    function apply(event) {
        console.log(event.target);
        const value = Object.fromEntries(new FormData($(event.target).parent('form').get(0)));

        console.log(songs[selected]);
        songs[selected].name = value.name;
        songs[selected].genre = value.genre;
        songs[selected].originalAuthor = value.originalAuthor;
        console.log(songs[selected]);

        selected = null;
        sync();
    }

    $('#button-apply').click(apply);
    $('#button-submit').click(event => {
        event.preventDefault();
        const data = {
            name: $('#album-name').val(),
            desc: $('#album-desc').val(),
            bandId: $('#album-band-id').val(),
            songs
        };

        fetch('{{ url_for("album.new") }}', {
            method: 'post',
            redirect: 'follow',
            body: JSON.stringify(data),
            headers: {
                'Content-Type': 'application/json'
            }
        }).then(response => {
            if (response.redirected) {
                window.location.href = response.url;
            }
        });

    })
    $(function () { sync(); });
</script>

{% endblock %}