views/album.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *
from datetime import datetime

album_bp = Blueprint('album', __name__)


@album_bp.route('/album/')
def index():
    albums = invoke(f'''
                    select (
                        select count(*) from Song where Song.AlbumID = Album.AlbumID
                    ) as count, 
                    exists (
                        select * from LikeAlbum where UserID = {session['userid']} and AlbumID = Album.AlbumID
                    ) as liked,
                    Album.*, Band.* from Album
                    inner join Band on Album.BandID = Band.BandID''').fetchall()

    return render_template('/album/index.html', albums=albums)


@album_bp.route('/album/new', methods=['GET', 'POST'])
def new():
    if request.method == 'GET':
        userid = session['userid']
        bands = invoke(f'''select * from Band b where exists (
                       select * from _UserToBand where UserID = {userid} and BandID = b.BandID
                       )''')
        return render_template('/album/new.html', bands=bands)
    
    if not request.is_json:
        abort(400)

    data = request.json
    name = data['name']
    desc = data['desc']
    band_id = data['bandId']
    date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    album_id = invoke_insertion(f'''insert into Album(AlbumName, AlbumDescription, ReleaseDate, BandID)
                                    values ("{name}", "{desc}", "{date}", {band_id})''')
    
    for i, item in enumerate(data['songs']):
        name = item['name']
        genre = item['genre']
        author = item['originalAuthor']
        invoke_insertion(f'''insert into Song(SongName, OriginalAuthor, Genre, AlbumID, `Order`)
                             values ("{name}", "{author}", "{genre}", {album_id}, {i + 1})''')
        
    return redirect(url_for('album.details', id=album_id))

@album_bp.route('/album/<int:id>')
def details(id: int):
    album = invoke(f'select * from Album where AlbumID = {id}').fetchone()

    if album is None:
        abort(404)

    rating = invoke(f'select AlbumID, avg(Rating) as rating, count(*) as `count` from Review group by AlbumID having AlbumID = {id}').fetchone()

    songs = invoke(f'select * from Song where AlbumID = {id} order by `Order` asc')
    user_review = invoke(f'select * from Review where AlbumID = {id} and UserID = {session['userid']}').fetchone() 
    liked_users = invoke(f'''select * from User user where exists (
                         select * from LikeAlbum where UserID = user.UserID and AlbumID = {id}
                         )''').fetchall()
    rel = invoke(f'select * from _UserToBand where BandID = {album['BandID']} and UserID = {session['userid']}').fetchone()
    
    editable = rel is not None or session['usertype'] == 'manager'

    return render_template('/album/details.html', album=album, songs=songs, rating=rating, user_review=user_review, liked_users=liked_users, editable=editable)

@album_bp.route('/album/<int:id>/like', methods=['POST'])
def like(id: int):
    userid = session['userid']

    rel = invoke(f'select * from LikeAlbum where UserID = {userid} and AlbumID = {id}').fetchone()

    if rel is None:
        invoke(f'insert into LikeAlbum values ({userid}, {id})')
        return { 'liked': True }
    else:
        invoke(f'delete from LikeAlbum where UserID = {userid} and AlbumID = {id}')
        return { 'liked': False }
    
@album_bp.route('/album/<int:id>/add', methods=['GET', 'POST'])
def add(id: int):
    if request.method == 'GET':
        album = invoke(f'select * from Album where AlbumID = {id}')
        songs = invoke(f'select * from Song where AlbumID = {id} order by `Order` asc').fetchall()
        return render_template('/album/add.html', album=album, songs=songs)
    
    pos = request.form['pos']
    name = request.form['name']
    oa = request.form['originalAuthor']
    genre = request.form['genre']

    invoke(f'update Song set `Order` = `Order` + 1 where AlbumID = {id} and `Order` > {pos}')
    invoke(f'''insert into Song(SongName, OriginalAuthor, Genre, AlbumID, `Order`)
           values ("{name}", "{oa}", "{genre}", {id}, {pos + 1})''')
    
    return redirect(url_for('album.details', id=id))

views/auth.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *
from datetime import datetime

auth_bp = Blueprint('auth', __name__)

@auth_bp.route("/auth/logout")
def logout():
    session.clear()
    return redirect(url_for("auth.login"))

@auth_bp.route("/auth/login", methods=['GET', 'POST'])  # 登录
def login():
    if request.method == 'GET':
        return render_template('auth/login.html')
    
    name = request.form.get("username")
    pwd = request.form.get("password")
    ans = invoke(f"select * from User where UserName = '{name}'")
    user = ans.fetchone()
    if user is None or user['Password'] != pwd:
        return render_template('auth/login.html', error="登录凭据无效")

    session.update({
        'userid': user['UserID'],
        'username': name,
        'usertype': user['Type'],
    })

    print(user)
    return redirect('/')


@auth_bp.route("/auth/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("auth/register.html")

    name = request.form.get("username")
    pwd = request.form.get("password")
    pwd2 = request.form.get("password2")
    type = request.form.get("userType")
    user = invoke(f"select * from User where UserName = '{name}'").fetchone()
    print(user)

    if pwd2 != pwd:
        return render_template('/auth/register.html', error="密码不一致")
    
    if user is not None:
        return render_template('/auth/register.html', error="该用户名已经存在")
    
    if type == '':
        return render_template('/auth/register.html', error="请选择用户类型")
    
    invoke(f"INSERT INTO User(UserName, Password, Type) VALUES ('{name}', '{pwd}', '{type}')")
    return redirect(url_for('auth.login'))

views/review.py
from flask import render_template, request, redirect, url_for, session, abort, Blueprint
from db import *

review_bp = Blueprint('review', __name__)

@review_bp.route('/review')
def index():
    reviews = invoke(f'''select * from Review
                     inner join Album on Album.AlbumID = Review.AlbumID
                     inner join User on User.UserID = Review.UserID''')
    
    return render_template('review/index.html', reviews=reviews)

@review_bp.route('/album/<int:album_id>/review/<int:user_id>')
def details(album_id: int, user_id: int):
    review = invoke(f'''select * from Review
                    inner join Album on Album.AlbumID = Review.AlbumID
                    inner join User on User.UserID = Review.UserID
                    where Review.AlbumID = {album_id} and Review.UserID = {user_id}''').fetchone()
    
    if review is None:
        abort(404)

    editable = review['UserID'] == session['userid'] or session['usertype'] == 'manager'

    return render_template('/review/details.html', review=review, editable=editable)

@review_bp.route('/album/<int:album_id>/review/')
def list(album_id: int):
    album = invoke(f'select * from Album where AlbumID = {album_id}').fetchone()

    if album is None:
        abort(404)

    reviews = invoke(f'''select * from Review
                       inner join User on Review.UserID = User.UserID
                       where AlbumID = {album_id}''')
    return render_template('/review/list.html', album=album, reviews=reviews)

@review_bp.route('/album/<int:album_id>/review/new', methods=['GET', 'POST'])
def new(album_id: int):
    if request.method == 'GET':
        album = invoke(f'select * from Album where AlbumID = {album_id}')
        return render_template('/review/new.html', album=album)
    
    rating = request.form['rating']
    comment = request.form['comment']

    invoke(f'''insert into Review(AlbumID, UserID, Rating, Comment)
           values ({album_id}, {session['userid']}, {rating}, "{comment}")''')
    
    return redirect(url_for('review.details', album_id=album_id, user_id=session['userid']))
    
@review_bp.route('/album/<int:album_id>/review/edit', methods=['GET', 'POST'])
def edit(album_id: int):
    if request.method == 'GET':
        review = invoke(f'''select * from Review
                          inner join Album on Album.AlbumID = Review.AlbumID
                          where Review.AlbumID = {album_id} and Review.UserID = {session['userid']}''').fetchone()
        
        if review is None:
            return redirect(url_for('review.new', album_id=album_id))
        
        return render_template('review/edit.html', review=review)
    
    rating = request.form['rating']
    comment = request.form['comment']

    invoke(f'''update Review set Rating = {rating}, Comment = "{comment}"
               where AlbumID = {album_id} and UserID = {session['userid']}''')

    return redirect(url_for('review.details', album_id=album_id, user_id=session['userid']))

views/song.py
from flask import Flask, render_template, request, redirect, url_for, session, abort, Blueprint
from db import *

song_bp = Blueprint('song', __name__)

@song_bp.route('/song/')
def index():
    songs = invoke(f'''
                   select 
                   exists (
                       select * from LikeSong where UserID = {session['userid']} and SongID = Song.SongID
                   ) as liked,
                   Song.*, Album.* from Song
                   inner join Album on Song.AlbumID = Album.AlbumID''').fetchall()
    return render_template('song/index.html', songs=songs)

@song_bp.route('/song/<int:id>')
def details(id: int):
    song = invoke(f'''select * from Song
                      inner join Album on Song.AlbumID = Album.AlbumID
                      where SongID = {id}''').fetchone()
    
    if song is None:
        abort(404)

    liked_users = invoke(f'''select * from User user where exists (
                         select * from LikeSong where UserID = user.UserID and SongID = {id}
                         )''').fetchall()
    
    rel = invoke(f'select * from _UserToBand where UserID = {session['userid']} and BandID = {song['BandID']}').fetchone()

    editable = rel is not None or session['usertype'] == 'manager'

    return render_template('/song/details.html', song=song, liked_users=liked_users, editable=editable)

@song_bp.route('/song/<int:id>/edit', methods=['GET', 'POST'])
def edit(id: int):
    if request.method == 'GET':
        song = invoke(f'select * from Song where SongID = {id}').fetchone()
        return render_template('/song/edit.html', song=song)
    
    name = request.form['name']
    oa = request.form['originalAuthor']
    genre = request.form['genre']

    invoke(f'update Song set SongName = "{name}", OriginalAuthor = "{oa}", Genre = "{genre}" where SongID = {id}')
    return redirect(url_for('song.details', id=id))

@song_bp.route('/song/<int:id>/like', methods=['POST'])
def like(id: int):
    userid = session['userid']

    rel = invoke(f'select * from LikeSong where UserID = {userid} and SongID = {id}').fetchone()

    if rel is None:
        invoke(f'insert into LikeSong values ({userid}, {id})')
        return { 'liked': True }
    else:
        invoke(f'delete from LikeSong where UserID = {userid} and SongID = {id}')
        return { 'liked': False }
    
@song_bp.route('/song/<int:id>/delete', methods=['POST'])
def delete(id: int):
    if 'userid' not in session:
        abort(403)

    song = invoke(f'select * from Song inner join Album on Album.AlbumID = Song.AlbumID where SongID = {id}').fetchone()

    if song is None:
        abort(404)

    rel = invoke(f'select * from _UserToBand where BandID = {song['BandID']} and UserID = {session['userid']}').fetchone()

    if rel is None:
        abort(403)

    pos = song['Order']
    invoke(f'update Song set `Order` = `Order` - 1 where `Order` > {pos}')
    invoke(f'delete from Song where SongID = {id}')

    return redirect(url_for('album.details', id=song['AlbumID']))

templates/_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
</head>

<body>
    <div class="ui top attached menu">
        <a class="item" href="/"><i class="icon home"></i>Home</a>
        <a class="item" href="{{ url_for('concert.index') }}"><i class="music icon"></i>Events</a>
        <a class="item" href="{{ url_for('album.index') }}"><i class="list icon"></i>Albums</a>
        <a class="item" href="{{ url_for('song.index') }}"><i class="music icon"></i>Songs</a>
        <a class="item" href="{{ url_for('band.index') }}"><i class="icon">💩</i>Bands</a>
        <a class="item" href="{{ url_for('review.index') }}"><i class="icon">💩</i>Reviews</a>
        <a class="item disabled" style="flex-grow: 1"></a>
        <div class="right menu">
            {% if session.userid %}
            <a href="{{ url_for('user.details', id=session.userid) }}" class="item"><i class="user icon"></i>My profile</a>
            <a href="{{ url_for('auth.logout') }}" class="item"><i class="sign out icon"></i>Logout</a>
            {% else %}
            <a href="{{ url_for('auth.login') }}" class="item"><i class="sign in icon"></i>Login</a>
            {% endif %}
        </div>
    </div>

    <style>
        .ui.top.attached.menu>.item,
        .ui.top.attached.menu>.menu>.item {
            flex-direction: column;
        }
    </style>

    <div class="ui container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

templates/index.html
{% extends '_base.html' %}

{% block title %}首页{% endblock %}

{% block body %}
<div class="ui inverted segment">
    <h1 class="ui inverted header">Welcome to the Band User Homepage</h1>
</div>
<div class="ui centered grid">
    <div class="row">
        <div class="twelve wide column">
            <div class="ui accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    喜欢的乐队
                </div>
                <div class="content">

                    <table class="ui celled table">
                        <thead>
                            <tr>
                                <th>乐队名</th>
                                <th>乐队简介</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for band in liked_bands %}
                            <tr>
                                <td><a href="{{ url_for('band.details', id=band.BandID) }}">{{ band.BandName }}</a></td>
                                <td>{{ band.BandDescription }}</td>
                                <td>
                                    <button class="ui icon button like-button" data-item-type="band"
                                        data-item-id="{{ band.BandID }}" data-liked="1">
                                        <i class="heart icon"></i>
                                    </button>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>暂无</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="twelve wide column">
            <div class="ui accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    喜欢的专辑
                </div>
                <div class="content">

                    <table class="ui celled table">
                        <thead>
                            <tr>
                                <th>专辑名</th>
                                <th>乐队</th>
                                <th>曲目数</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for album in liked_albums %}
                            <tr>
                                <td><a href="{{ url_for('album.details', id=album.AlbumID) }}">{{ album.AlbumName }}</a>
                                </td>
                                <td>{{ album.BandName }}</td>
                                <td>{{ album.count }}</td>

                                <td>
                                    <button class="ui icon button like-button" data-item-type="album"
                                        data-item-id="{{ album.AlbumID }}" data-liked="1">
                                        <i class="heart icon"></i>
                                    </button>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>暂无</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="twelve wide column">
            <div class="ui accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    喜欢的歌曲
                </div>
                <div class="content">

                    <table class="ui celled table">
                        <thead>
                            <tr>
                                <th>曲名</th>
                                <th>原作</th>
                                <th>风格</th>
                                <th>所属专辑</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in liked_songs %}
                            <tr>
                                <td><a href="{{ url_for('song.details', id=song.SongID) }}">{{ song.SongName }}</a></td>
                                <td>{{ song.OriginalAuthor }}</td>
                                <td>{{ song.Genre }}</td>
                                <td><a href="{{ url_for('album.details', id=song.AlbumID) }}">{{ song.AlbumName }}</a>
                                </td>

                                <td>
                                    <button class="ui icon button like-button" data-item-type="song"
                                        data-item-id="{{ song.SongID }}" data-liked="1">
                                        <i class="heart icon"></i>
                                    </button>
                                </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>暂无</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="twelve wide column">
            <div class="ui accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    参加的演出
                </div>
                <div class="content">

                    <table class="ui celled table">
                        <thead>
                            <tr>
                                <th>演出名</th>
                                <th>演出时间</th>
                                <th>参演乐队</th>
                                <th>演出地点</th>
                                <th>票号</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in participation %}
                            <tr>
                                <td><a href="{{ url_for('concert.details', id=item.ConcertID) }}">{{ item.ConcertName
                                        }}</a>
                                </td>
                                <td>{{ item.ConcertDate }}</td>
                                <td>{{ item.BandName }}</td>
                                <td>{{ item.Location }}</td>
                                <td>{{ item.TicketNumber }}</td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>暂无</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="twelve wide column">
            <div class="ui accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    评分最高的专辑
                </div>
                <div class="content">

                    <table class="ui celled table">
                        <thead>
                            <tr>
                                <th>专辑名</th>
                                <th>乐队</th>
                                <th>曲目数</th>
                                <th>平均评分</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for album in top_albums %}
                            <tr>
                                <td><a href="{{ url_for('album.details', id=album.AlbumID) }}">{{ album.AlbumName }}</a></td>
                                <td><a href="{{ url_for('band.details', id=album.BandID) }}">{{ album.BandName }}</a></td>
                                <td>{{ album.count }}</td>
                                <td>{{ album.avg_rating }}</td>
                            </tr>
                            {% else %}
                            <tr>
                                <td>暂无</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('.ui.accordion').accordion();
    $('.like-button').click(function () {
        $(this).addClass('disabled');
        const itemType = $(this).data('item-type');
        const itemId = $(this).data('item-id')
        fetch(`/${itemType}/${itemId}/like`, {
            method: 'POST'
        })
            .then(response => response.json())
            .then(data => {
                $(this).removeClass('disabled');
                if (data.liked === false) {
                    $(this).find('i.icon').addClass('outline');
                }
                else {
                    $(this).find('i.icon').removeClass('outline');
                }
            });
    });
</script>

{% endblock %}